=== kanon-centos/TSObeliskSimulator/src/TSObeliskSimulator/mapdata/MapList.dtd
<!ELEMENT MapList (Map+)>
<!ELEMENT Map (DefCastle?, Crystal?)>
<!ATTLIST Map
  MapID           ID    #REQUIRED    
  Name            CDATA #REQUIRED
  ImageUrl        CDATA #REQUIRED
  KeepSetDistance CDATA #IMPLIED
>
<!ELEMENT ImageUrl (#PCDATA)>
<!ELEMENT DefCastle (Position)>
<!ELEMENT Crystal (Position+)>
<!ELEMENT Position EMPTY>
<!ATTLIST Position X CDATA #REQUIRED>
<!ATTLIST Position Y CDATA #REQUIRED>

=== kanon-centos/TSObeliskSimulator/src/TSObeliskSimulator/mapdata/MapList.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE MapList SYSTEM "MapList.dtd">
<MapList>

  <Map MapID="M010" Name="三字" ImageUrl="mapdata/image/3.jpg" KeepSetDistance ="144">
    <DefCastle>
      <Position X="138" Y="201" />
    </DefCastle>
    <Crystal>
      <Position X="24" Y="38" />
      <Position X="128" Y="62" />
      <Position X="128" Y="128" />
      <Position X="110" Y="196" />
      <Position X="232" Y="226" />
    </Crystal>
  </Map>

  <Map MapID="M020" Name="三連隕石" ImageUrl="mapdata/image/3inseki.jpg">
    <DefCastle>
      <Position X="152" Y="77" />
    </DefCastle>
    <Crystal>
      <Position X="77" Y="67" />
      <Position X="146" Y="86" />
      <Position X="125" Y="122" />
      <Position X="126" Y="142" />
      <Position X="99" Y="181" />
      <Position X="200" Y="199" />
    </Crystal>
  </Map>

  <Map MapID="M030" Name="Ｅ字（E3城）" ImageUrl="mapdata/image/e.jpg">
    <DefCastle>
      <Position X="70" Y="128" />
    </DefCastle>
    <Crystal>
      <Position X="78" Y="128" />
      <Position X="50" Y="46" />
      <Position X="142" Y="58" />
      <Position X="193" Y="127" />
      <Position X="164" Y="160" />
      <Position X="86" Y="167" />
    </Crystal>
  </Map>

  <Map MapID="M031" Name="Ｅ字（G5城）" ImageUrl="mapdata/image/e.jpg">
    <DefCastle>
      <Position X="139" Y="192" />
    </DefCastle>
    <Crystal>
      <Position X="63" Y="65" />
      <Position X="143" Y="59" />
      <Position X="94" Y="128" />
      <Position X="203" Y="127" />
      <Position X="48" Y="190" />
      <Position X="149" Y="201" />
    </Crystal>
  </Map>

  <Map MapID="M040" Name="φ字（C6城）" ImageUrl="mapdata/image/fai.jpg">
    <DefCastle>
      <Position X="178" Y="79" />
    </DefCastle>
    <Crystal>
      <Position X="59" Y="67" />
      <Position X="139" Y="77" />
      <Position X="168" Y="84" />
      <Position X="128" Y="136" />
      <Position X="70" Y="175" />
      <Position X="115" Y="200" />
      <Position X="195" Y="214" />
    </Crystal>
  </Map>

  <Map MapID="M041" Name="φ字（F6城）" ImageUrl="mapdata/image/fai.jpg">
    <DefCastle>
      <Position X="166" Y="182" />
    </DefCastle>
    <Crystal>
      <Position X="181" Y="190" />
      <Position X="195" Y="214" />
      <Position X="54" Y="215" />
      <Position X="128" Y="136" />
      <Position X="59" Y="67" />
      <Position X="27" Y="89" />
      <Position X="213" Y="34" />
    </Crystal>
  </Map>

  <Map MapID="M050" Name="群島1" ImageUrl="mapdata/image/guntou.jpg">
    <DefCastle>
      <Position X="92" Y="60" />
    </DefCastle>
    <Crystal>
      <Position X="84" Y="75" />
      <Position X="105" Y="101" />
      <Position X="59" Y="180" />
      <Position X="193" Y="44" />
      <Position X="157" Y="154" />
      <Position X="180" Y="202" />
    </Crystal>
  </Map>

  <Map MapID="M060" Name="廃街" ImageUrl="mapdata/image/haimachi.png">
    <DefCastle>
      <Position X="156" Y="157" />
    </DefCastle>
    <Crystal>
      <Position X="80" Y="82" />
      <Position X="137" Y="81" />
      <Position X="217" Y="63" />
      <Position X="47" Y="128" />
      <Position X="157" Y="134" />
      <Position X="191" Y="204" />
      <Position X="110" Y="201" />
    </Crystal>
  </Map>

  <Map MapID="M070" Name="人字1" ImageUrl="mapdata/image/hito1.jpg" KeepSetDistance="160">
    <DefCastle>
      <Position X="70" Y="166" />
    </DefCastle>
    <Crystal>
      <Position X="75" Y="176" />
      <Position X="125" Y="194" />
      <Position X="131" Y="149" />
      <Position X="152" Y="115" />
      <Position X="135" Y="50" />
      <Position X="184" Y="58" />
    </Crystal>
  </Map>

  <Map MapID="M080" Name="瓢箪1" ImageUrl="mapdata/image/hyoutan.jpg">
    <DefCastle>
      <Position X="178" Y="79" />
    </DefCastle>
    <Crystal>
      <Position X="84" Y="37" />
      <Position X="64" Y="76" />
      <Position X="209" Y="60" />
      <Position X="134" Y="122" />
      <Position X="61" Y="183" />
      <Position X="183" Y="209" />
      <Position X="218" Y="185" />
    </Crystal>
  </Map>

  <Map MapID="M090" Name="街道（B6城）" ImageUrl="mapdata/image/kaidou.jpg">
    <DefCastle>
      <Position X="190" Y="63" />
    </DefCastle>
    <Crystal>
      <Position X="70" Y="73" />
      <Position X="131" Y="67" />
      <Position X="182" Y="51" />
      <Position X="166" Y="120" />
      <Position X="102" Y="154" />
      <Position X="22" Y="202" />
      <Position X="159" Y="151" />
    </Crystal>
  </Map>

  <Map MapID="M091" Name="街道（F3城）" ImageUrl="mapdata/image/kaidou.jpg">
    <DefCastle>
      <Position X="84" Y="172" />
    </DefCastle>
    <Crystal>
      <Position X="73" Y="179" />
      <Position X="53" Y="146" />
      <Position X="69" Y="69" />
      <Position X="129" Y="126" />
      <Position X="178" Y="83" />
      <Position X="205" Y="124" />
      <Position X="198" Y="191" />
    </Crystal>
  </Map>

  <Map MapID="M092" Name="街道（B5城）" ImageUrl="mapdata/image/kaidou.jpg" KeepSetDistance="152">
    <DefCastle>
      <Position X="130" Y="56" />
    </DefCastle>
    <Crystal>
      <Position X="131" Y="67" />
      <Position X="182" Y="51" />
      <Position X="205" Y="124" />
      <Position X="205" Y="196" />
      <Position X="124" Y="217" />
      <Position X="22" Y="202" />
    </Crystal>
  </Map>

  <Map MapID="M093" Name="街道（C3城）" ImageUrl="mapdata/image/kaidou.jpg">
    <DefCastle>
      <Position X="75" Y="80" />
    </DefCastle>
    <Crystal>
      <Position X="61" Y="56" />
      <Position X="185" Y="63" />
      <Position X="210" Y="115" />
      <Position X="90" Y="195" />
      <Position X="34" Y="209" />
      <Position X="185" Y="190" />
    </Crystal>
  </Map>

  <Map MapID="M100" Name="渓谷（F6城）" ImageUrl="mapdata/image/keikoku.jpg">
    <DefCastle>
      <Position X="171" Y="167" />
    </DefCastle>
    <Crystal>
      <Position X="50" Y="66" />
      <Position X="121" Y="63" />
      <Position X="188" Y="43" />
      <Position X="55" Y="213" />
      <Position X="163" Y="166" />
      <Position X="210" Y="202" />
    </Crystal>
  </Map>

  <Map MapID="M101" Name="渓谷（C4城）" ImageUrl="mapdata/image/keikoku.jpg" KeepSetDistance="126">
    <DefCastle>
      <Position X="103" Y="68" />
    </DefCastle>
    <Crystal>
      <Position X="67" Y="59" />
      <Position X="113" Y="81" />
      <Position X="215" Y="71" />
      <Position X="178" Y="141" />
      <Position X="191" Y="172" />
      <Position X="122" Y="198" />
      <Position X="70" Y="173" />
    </Crystal>
  </Map>

  <Map MapID="M110" Name="新始まり" ImageUrl="mapdata/image/new_hajimari.jpg">
    <DefCastle>
      <Position X="165" Y="167" />
    </DefCastle>
    <Crystal>
      <Position X="150" Y="160" />
      <Position X="198" Y="191" />
      <Position X="41" Y="215" />
      <Position X="56" Y="134" />
      <Position X="71" Y="45" />
      <Position X="170" Y="51" />
      <Position X="202" Y="11" />
    </Crystal>
  </Map>

  <Map MapID="M120" Name="新中央島（D7城）" ImageUrl="mapdata/image/new_cyuoujima.jpg">
    <DefCastle>
      <Position X="197" Y="108" />
    </DefCastle>
    <Crystal>
      <Position X="197" Y="123" />
      <Position X="148" Y="146" />
      <Position X="126" Y="196" />
      <Position X="140" Y="44" />
      <Position X="119" Y="89" />
      <Position X="83" Y="127" />
    </Crystal>
  </Map>

  <Map MapID="M121" Name="新中央島（C6城）" ImageUrl="mapdata/image/new_cyuoujima.jpg">
    <DefCastle>
      <Position X="167" Y="72" />
    </DefCastle>
    <Crystal>
      <Position X="142" Y="41" />
      <Position X="210" Y="52" />
      <Position X="210" Y="102" />
      <Position X="49" Y="137" />
      <Position X="53" Y="191" />
      <Position X="109" Y="212" />
    </Crystal>
  </Map>

  <Map MapID="M130" Name="新古戦場" ImageUrl="mapdata/image/new_kosenjyou.jpg">
    <DefCastle>
      <Position X="195" Y="131" />
    </DefCastle>
    <Crystal>
      <Position X="187" Y="136" />
      <Position X="141" Y="48" />
      <Position X="113" Y="84" />
      <Position X="56" Y="135" />
      <Position X="125" Y="159" />
      <Position X="98" Y="218" />
    </Crystal>
  </Map>
 
  <Map MapID="M140" Name="新乙字" ImageUrl="mapdata/image/new_otu.jpg">
    <DefCastle>
      <Position X="107" Y="173" />
    </DefCastle>
    <Crystal>
      <Position X="74" Y="69" />
      <Position X="157" Y="79" />
      <Position X="176" Y="58" />
      <Position X="120" Y="120" />
      <Position X="149" Y="107" />
      <Position X="119" Y="169" />
      <Position X="176" Y="177" />
      <Position X="82" Y="196" />
    </Crystal>
  </Map>

  <Map MapID="M150" Name="Ｏ字" ImageUrl="mapdata/image/o.jpg">
    <DefCastle>
      <Position X="159" Y="67" />
    </DefCastle>
    <Crystal>
      <Position X="149" Y="75" />
      <Position X="69" Y="97" />
      <Position X="143" Y="119" />
      <Position X="192" Y="110" />
      <Position X="76" Y="156" />
      <Position X="180" Y="160" />
      <Position X="127" Y="181" />
    </Crystal>
  </Map>

  <Map MapID="M160" Name="旧中央島" ImageUrl="mapdata/image/old_cyuoujima.jpg">
    <DefCastle>
      <Position X="197" Y="108" />
    </DefCastle>
    <Crystal>
      <Position X="197" Y="123" />
      <Position X="193" Y="39" />
      <Position X="120" Y="42" />
      <Position X="151" Y="97" />
      <Position X="117" Y="135" />
      <Position X="58" Y="118" />
      <Position X="150" Y="213" />
    </Crystal>
  </Map>

  <Map MapID="M170" Name="旧古戦場" ImageUrl="mapdata/image/old_kosenjyou.jpg">
    <DefCastle>
      <Position X="133" Y="61" />
    </DefCastle>
    <Crystal>
      <Position X="110" Y="57" />
      <Position X="188" Y="25" />
      <Position X="225" Y="74" />
      <Position X="88" Y="220" />
      <Position X="38" Y="217" />
      <Position X="26" Y="176" />
    </Crystal>
  </Map>

  <Map MapID="M180" Name="旧乙字" ImageUrl="mapdata/image/old_otu.jpg">
    <DefCastle>
      <Position X="135" Y="65" />
    </DefCastle>
    <Crystal>
      <Position X="68" Y="65" />
      <Position X="147" Y="71" />
